### PR TITLE
Update .gitattributes

### PR DESCRIPTION
**Pull request by GrahamCampbell**
This should fix the issues you've been having with StyleCI.

### CODE REVIEW

**Comment by niels-nijens** [comment]
Looks like we've had the same idea (see #149). Great minds think alike?

**Comment by niels-nijens** [comment]
I'll close this one and merge my own instead.

**Comment by GrahamCampbell** [comment]
:)

**Comment by RonRademaker** [comment]
Uh, Niels' changes don't cover Grahams changes right?

**Comment by GrahamCampbell** [comment]
No, they do. ;)

**Pull request closed without merging**
